In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [15]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [16]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [22]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [23]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [26]:
np.random.rand(5)

array([ 0.74815388,  0.80070823,  0.74229432,  0.28295044,  0.31838158])

In [27]:
np.random.rand(5,5)

array([[ 0.45946501,  0.86626376,  0.04232711,  0.00853359,  0.60728148],
       [ 0.50939442,  0.46220081,  0.71599202,  0.74819014,  0.51790238],
       [ 0.80084018,  0.74730732,  0.2981797 ,  0.63144913,  0.25605401],
       [ 0.5311132 ,  0.35336922,  0.66608815,  0.70532534,  0.11695312],
       [ 0.81856626,  0.70190022,  0.67419159,  0.71868757,  0.09106702]])

In [28]:
np.random.randn(4,4)

array([[ 0.27813947,  1.69976068, -0.39686828,  0.39177097],
       [-0.95456409, -0.34198728,  1.42098265, -0.95128689],
       [ 0.68285766,  0.35136136, -0.19236429,  0.68593064],
       [-0.8310822 ,  0.82842481, -0.52303603,  0.42915957]])

In [30]:
np.random.randint(1,100, 10)

array([96, 71, 31, 32, 38, 12, 33, 11, 78,  1])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,10)

In [34]:
ranarr

array([48, 24, 42, 19,  4, 33, 18, 34,  4,  0])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr

array([48, 24, 42, 19,  4, 33, 18, 34,  4,  0])

In [37]:
ranarr.max()

48

In [39]:
ranarr.argmin()

9

In [40]:
ranarr.argmax()

0

In [41]:
arr.shape

(25,)

In [47]:
arr = arr.reshape(5,5)

In [48]:
arr.shape

(5, 5)

In [50]:
new.shape

(5, 5)

In [51]:
arr.dtype

dtype('int32')

In [52]:
from numpy.random import randint

In [53]:
randint(2,10)

9